kind: pipeline
name: production
steps:
- name: docker  
  image: plugins/docker:17.12
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: Sierra1011/portwarden-server-prod
    dockerfile: Dockerfile.Build
    target: production
    salt:
      from_secret: Salt
    build_args:
      - Salt=$PLUGIN_SALT
    auto_tag: true
