version: '3'

services:

  salt_generator:
    image: Sierra1011/portwarden-server-dev:v0.1.1
    environment:
      - Salt=${Salt}
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
    command:
      go run ./utils/generate_salt_file.go

  scheduler:
    image: Sierra1011/portwarden-server-dev:v0.1.1
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/scheduler

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: Sierra1011/portwarden-server-dev:v0.1.1
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/go/src/github.com/Sierra1011/portwarden
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/worker

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  frontend:
    image: Sierra1011/portwarden-frontend:0.1.1
    restart: always
    ports:
    - "8000:8000"
