version: '3'

services:

  scheduler:
    image: Sierra1011/portwarden-server-prod:0.1.2
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    ports:
      - 5000:5000
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/scheduler
    command:
      ./scheduler
    labels: 
      kompose.service.expose: "true"
      kompose.service.type: "loadbalancer"

  redis:
    image: redis

  worker:
    image: Sierra1011/portwarden-server-prod:0.1.2
    stdin_open: true
    tty: true
    environment:
      - BITWARDENCLI_APPDATA_DIR=/BitwardenCLI
      - BackupDefaultSleepMilliseconds=20
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    working_dir:
      /go/src/github.com/Sierra1011/portwarden/web/worker
    command:
      ./worker

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    labels: 
      kompose.service.expose: "true"
      kompose.service.type: "loadbalancer"

  frontend:
    image: Sierra1011/portwarden-frontend:0.1.1
    restart: always
    ports:
    - "8000:8000"
